### ISSUE TITLE
Vite support

### ISSUE THREAD

**Issue by Dauta** [Tschrock/esbuild-plugin-wasm#2]
Hi! 
Thank you so much for this plugin! Love how seamless it makes working with wasm files with esbuild.
I'm looking to move my project from plain esbuild to vite. I've been really liking vite's built in support for HMR and other features.
Unfortunately, it seems that out of the box support for loading wasm isn't really as straightforward. Do you know if it would be possible to port this plugin to work with Vite? 
Thanks again!

**Comment by Tschrock** [comment]
It looks like there is now a Vite plugin with similar functionality at <https://github.com/Menci/vite-plugin-wasm>
